uniatlas/uniatlas/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

uniatlas/website/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('resultpage/', views.resultpage),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('login/signup/', views.signup),
    path('unisozluk/', views.unisozluk),
    path('unipage/', views.unipage),
    path('profile/', views.profile),
    path('unilist/', views.unilist, name="unilist"),
    path('assistant/', views.assistant),
    path('userprofile/', views.userprofile),
    path('uniedit/', views.uniedit),
    path('settings/', views.settings),
    path('settings2/', views.settings2),
    path('admin/controlpanel', views.controlpanel, name="controlpanel"),
    path('admin/add/university', views.add_uni),
    path('admin/delete/university/<int:pk>', views.delete_uni),
    path('admin/edit/university/<int:pk>', views.edit_university),
    path('admin/add/faculty', views.add_faculty),
    path('admin/delete/faculty/<int:pk>', views.delete_faculty),
    path('admin/edit/faculty/<int:pk>', views.edit_faculty),
    path('admin/add/departmant', views.add_departmant),
    path('admin/edit/departmant/<int:pk>', views.edit_departmant),
    path('admin/delete/departmant/<int:pk>', views.delete_departmant)
]

uniatlas/website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

User._meta.get_field('email')._unique = True


SCHOLARSHIP_CHOICES = [
    (-1, 'Ücretsiz'),
    (0, '%100 Burslu'),
    (1, '%75 Burslu'),
    (2, '%50 Burslu'),
    (3, '%25 Burslu')
]

TOTAL_YEAR_CHOICES = [
    ("tdegree", 'İki Yıllık'),
    ("fdegree", 'Dört Yıllık'),
]

EDU_FIELD_CHOICES = [
    ("mf", 'Sayısal'),
    ("tm", 'Eşit Ağırlık'),
    ("söz", 'Sözel'),
    ("dil", 'Dil')
]


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Enrolee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    STATUS_CHOICES = [
        (0, 'Liseli'),
        (1, 'Üniversiteli'),
        (2, 'Mezun'),

    ]

    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=1
    )

    def __str__(self):
        return self.user.username


class University(models.Model):
    image = models.ImageField(upload_to='uni_image', null=True, blank=True, default='uni_image/default')
    name = models.CharField(max_length=100, unique=True)
    city = models.CharField(max_length=100)
    history = models.TextField(max_length=500)

    TYPE_CHOICES = [
        ("feepaying", 'Özel Okul'),
        ("public", 'Devlet Okulu')
    ]

    types = models.CharField(
        choices=TYPE_CHOICES,
        default=None,
        max_length=100
    )

    def __str__(self):
        return self.name


class UniversityTag(models.Model):
    campus_info = models.CharField(max_length=100)
    university = models.ForeignKey(University, on_delete=models.CASCADE)

    def __str__(self):
        return self


class Faculties(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    edu_field = models.CharField(choices=EDU_FIELD_CHOICES, default=None, max_length=100)

    def __str__(self):
        return f'{self.university.name}-{self.name}'

    class Meta:
        unique_together = (('university', 'name'),)


class Department(models.Model):
    faculty = models.ForeignKey(Faculties, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    total_year = models.CharField(choices=TOTAL_YEAR_CHOICES, max_length=100)
    scholarship = models.IntegerField(choices=SCHOLARSHIP_CHOICES, default=-1)
    score = models.FloatField(default=0, validators=[MaxValueValidator(600), MinValueValidator(0)])

    def __str__(self):
        return self.name

    class Meta:
        unique_together = (('scholarship', 'name'),)


class Comment(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    enrolee = models.ForeignKey(Enrolee, on_delete=models.CASCADE)
    rate = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(5)])
    text = models.TextField(max_length=500)
    date = models.DateTimeField()

    def __str__(self):
        return self.text


class Unitable(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    student = models.ForeignKey(Enrolee, on_delete=models.CASCADE)

    def __str__(self):
        return self

uniatlas/website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import (
    get_user_model,

)
from .models import University, Faculties, Department, SCHOLARSHIP_CHOICES, TOTAL_YEAR_CHOICES, EDU_FIELD_CHOICES

User = get_user_model()


class CreateUserForm(UserCreationForm):
    EDU_CHOICES = [('Eğitim',(('1','Lise'),('1','Üniversite'),('1','Mezun'),))];
    username = forms.CharField(label='username', widget=forms.TextInput(attrs={'placeholder':'Kullanıcı Adı'}))
    email = forms.EmailField(label='email', widget=forms.TextInput(attrs={'placeholder': 'E-mail'}))
    education = forms.ChoiceField(widget=forms.Select, choices=EDU_CHOICES, )
    password1 = forms.CharField(label='password1', widget=forms.PasswordInput(attrs={'placeholder': 'Şifre'}))
    password2 = forms.CharField(label='password2', widget=forms.PasswordInput(attrs={'placeholder': 'Şifre(Tekrar)'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'education', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = False
        self.fields['email'].label = False
        self.fields['education'].label = False
        self.fields['password1'].label = False
        self.fields['password2'].label = False


class PasswordResetRequestForm(forms.Form):
    email_or_username = forms.CharField(label=("Email Or Username"), max_length=254)


class UniForm(forms.ModelForm):
    image = forms.ImageField(label='', required=False)
    class Meta:
        model = University
        fields = [
            'image',
            'name',
            'city',
            'history',
            'types'
        ]


class FacultyForm(forms.ModelForm):
    class Meta:
        model = Faculties
        fields = [
            'university',
            'name',
            'edu_field'
        ]


class DepartForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = [
            'faculty',
            'name',
            'scholarship',
            'total_year',
            'score'
        ]

class searchbyuni(forms.Form):
    search_key = forms.CharField()


class UniSearchForm(forms.Form):
    total_year = forms.ChoiceField(label='Türü', choices=TOTAL_YEAR_CHOICES, required=False)
    university = forms.ModelChoiceField(label='Üniversite', queryset=University.objects.all(), required=False)
    scholarship = forms.MultipleChoiceField(label='Burs Tipi', choices=SCHOLARSHIP_CHOICES, required=False)
    score = forms.FloatField(label='Puan', required=False)
    edu_field = forms.ChoiceField(label='Alan', choices=EDU_FIELD_CHOICES, required=False)
    city = forms.MultipleChoiceField(label='Şehir', choices=[], required=False)
    
    def __init__(self, *args, **kwargs):
        super(UniSearchForm, self).__init__(*args, **kwargs)
        self.fields['city'].choices = University.objects.values_list('city', 'city').distinct()

uniatlas/website/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.template.defaultfilters import register

from .models import Enrolee, Admin, University, Faculties, Department, SCHOLARSHIP_CHOICES
from .forms import UniForm, FacultyForm, DepartForm, searchbyuni, UniSearchForm, CreateUserForm


# Create your views here.

def home(request):
    return render(request, 'website/home.html')


def resultpage(request):
    form = UniSearchForm(request.POST or None)

    if form.is_valid():
        results = []
        if form.cleaned_data['university']:
            faculties = Faculties.objects.filter(university=form.cleaned_data['university'])
            results.append(Department.objects.filter(faculty__in=faculties))

        if form.cleaned_data['total_year']:
            results.append(Department.objects.filter(total_year=form.cleaned_data['total_year']))
        if form.cleaned_data['scholarship']:
            results.append(Department.objects.filter(scholarship__in=form.cleaned_data['scholarship']))
        if form.cleaned_data['score'] is not None:
            results.append(Department.objects.filter(score__lte=form.cleaned_data['score']))
        if form.cleaned_data['edu_field']:
            for faculty in Faculties.objects.filter(edu_field=form.cleaned_data['edu_field']):
                results.append(Department.objects.filter(faculty=faculty))

        if form.cleaned_data['city']:
            for university in University.objects.filter(city__in=form.cleaned_data['city']):
                results.append(Department.objects.filter(faculty__in=Faculties.objects.filter(university=university)))
        if len(results) > 0:
            search_results = set(results[0])
            for result in results[1:]:
                search_results = search_results.intersection(result)
        else:
            search_results = Department.objects.all()

    context = {
        'data': search_results,
    }
    return render(request, 'website/resultpage.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            return redirect('controlpanel')
        else:
            return redirect('unilist')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                if request.user.is_superuser:
                    return redirect('controlpanel')
                else:
                    return redirect('unilist')
            else:
                messages.info(request, 'Kullanıcı Adı veya Şifre hatalı.')
    return render(request, 'website/login.html')


def logoutUser(request):
    logout(request)
    return redirect('login')


def signup(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            return redirect('controlpanel')
        else:
            return redirect('unilist')
    else:
        form = CreateUserForm();

        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                registered_user = form.save()
                Enrolee(user=registered_user).save()
                return redirect('login')

    return render(request, 'website/signup.html', {'form': form})


def unisozluk(request):
    return render(request, 'website/unisozluk.html')


def unipage(request):
    return render(request, 'website/unipage.html')


def uniedit(request):
    return render(request, 'website/uniedit.html')


@login_required(login_url='login')
def profile(request):
    return render(request, 'website/profile.html')


@login_required(login_url='login')
def unilist(request):
    return render(request, 'website/unilist.html')


@register.filter
def to_class_name(value):
    return value.__class__.__name__


def controlpanel(request):
    item = request.GET
    uni_form = searchbyuni(item or None)

    results = []

    scholarships = {
        -1: 'Ücretsiz',
        0: '%100 Burslu',
        1: '%75 Burslu',
        2: '%50 Burslu',
        3: '%25 Burslu'
    }
    if uni_form.is_valid():
        unis = University.objects.filter(name__contains=uni_form.cleaned_data['search_key'])
    else:
        unis = University.objects.all()

    for i, university in enumerate(unis):
        uni_obj = {}
        uni_obj['name'] = university.name
        uni_obj['type'] = 'university'
        uni_obj['id'] = f'{university.pk}-{university.name}'
        uni_obj['pk'] = university.pk
        results.append(uni_obj)
        faculties = Faculties.objects.filter(university=university)
        for faculty in faculties:
            faculty_obj = {}
            faculty_obj['name'] = faculty.name
            faculty_obj['parent_id'] = uni_obj['id']
            faculty_obj['id'] = f'{faculty.pk}-{faculty.name}'
            faculty_obj['pk'] = faculty.pk
            faculty_obj['type'] = 'faculty'
            results.append(faculty_obj)
            departmants = Department.objects.filter(faculty=faculty)
            for dep in departmants:
                dep_obj = {}
                dep_obj['name'] = f'{dep.name}-{scholarships[dep.scholarship]}'
                dep_obj['parent_id'] = faculty_obj['id']
                dep_obj['id'] = f'{dep.pk}-{dep.name}'
                dep_obj['pk'] = dep.pk
                dep_obj['type'] = 'departmant'
                results.append(dep_obj)

    context = {
        'data': results
    }
    return render(request, 'website/controlpanel.html', context)


def assistant(request):
    form = UniSearchForm(None)
    context = {
        'form': form
    }
    return render(request, 'website/assistant.html', context)


def userprofile(request):
    return render(request, 'website/userprofile.html')


@login_required(login_url='login')
def settings(request):
    return render(request, 'website/settings.html')


@login_required(login_url='login')
def settings2(request):
    return render(request, 'website/settings2.html')


@login_required
def add_uni(request):
    user = request.user
    admin = Admin.objects.filter(user=user)

    if len(admin) > 0 or True:
        form = UniForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            print(form.cleaned_data)
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect('/admin/controlpanel')

    context = {
        "form": form
    }
    return render(request, 'website/adduni.html', context)


@login_required
def add_faculty(request):
    user = request.user
    admin = Admin.objects.filter(user=user)

    if len(admin) > 0 or True:
        faculty_form = FacultyForm(request.POST or None)
        if faculty_form.is_valid():
            faculty_form.save()
            return HttpResponseRedirect('/admin/controlpanel')

    context = {
        "faculty_form": faculty_form
    }
    return render(request, 'website/add_faculty.html', context)


@login_required
def edit_faculty(request, pk):
    detail = get_object_or_404(Faculties, pk=pk)
    form = FacultyForm(request.POST or None, instance=detail)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/admin/controlpanel')

    context = {
        "faculty_form": form,
        'edit': 'true',
        'pk': pk
    }
    return render(request, 'website/add_faculty.html', context)


@login_required
def edit_university(request, pk):
    detail = get_object_or_404(University, pk=pk)
    form = UniForm(request.POST or None, instance=detail)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect('/admin/controlpanel')

    context = {
        "form": form,
        'edit': 'true',
        'pk': pk
    }
    return render(request, 'website/adduni.html', context)


@login_required
def edit_departmant(request, pk):
    detail = get_object_or_404(Department, pk=pk)
    form = DepartForm(request.POST or None, instance=detail)

    if form.is_valid():
        uni = form.cleaned_data['faculty'].university
        if uni.types == 'public' and form.cleaned_data['scholarship'] != -1:
            form.add_error('scholarship', 'Devlet üniversitelerinde burs seçilemez!')
        elif uni.types == 'feepaying' and form.cleaned_data['scholarship'] == -1:
            form.add_error('scholarship', 'Özel üniversitelerinde ücretsiz seçilemez!')
        else:
            form.save()
            return HttpResponseRedirect('/admin/controlpanel')

    context = {
        "departmant_form": form,
        'edit': 'true',
        'pk': pk
    }
    return render(request, 'website/add_departmant.html', context)


@login_required
def add_departmant(request):
    user = request.user
    admin = Admin.objects.filter(user=user)

    if len(admin) > 0 or True:
        departmant_form = DepartForm(request.POST or None)
        if departmant_form.is_valid():
            uni = departmant_form.cleaned_data['faculty'].university
            if uni.types == 'public' and departmant_form.cleaned_data['scholarship'] != -1:
                departmant_form.add_error('scholarship', 'Devlet üniversitelerinde burs seçilemez!')
            elif uni.types == 'feepaying' and departmant_form.cleaned_data['scholarship'] == -1:
                departmant_form.add_error('scholarship', 'Özel üniversitelerinde ücretsiz seçilemez!')
            else:
                departmant_form.save()
                return HttpResponseRedirect('/admin/controlpanel')

    context = {
        "departmant_form": departmant_form
    }
    return render(request, 'website/add_departmant.html', context)


@login_required
def delete_uni(request, pk):

uniatlas/website/templates/website/add_departmant.html
{% include 'website/main.html' %}

{% load static %}
{% load crispy_forms_tags %}


<link rel="stylesheet" type="text/css" href="{% static "css/unisozluk_login.css" %}">

{% block content %}

    <div class="d-flex flex-row justify-content-center">
        <div class="w-25">
            <h2>Departman Ekle</h2>
            <form
                    {% if edit %}
                        action="/admin/edit/departmant/{{ pk }}"
                    {% else %}
                        action="/admin/add/departmant"
                    {% endif %}
                    method="post" class="d-flex flex-column justify-content-center">
                {% csrf_token %}
                {{ departmant_form|crispy }}
                <div class="w-100 d-flex justify-content-center">
                    <button class="w-50 btn btn-primary" type="submit">Gönder</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

uniatlas/website/templates/website/add_faculty.html
{% include 'website/main.html' %}

{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" type="text/css" href="{% static "css/unisozluk_login.css" %}">

{% block content %}

    <div class="w-100 d-flex flex-row justify-content-center">
        <div class="w-25">
            <h2>Fakülte Ekle</h2>
            <form
                    {% if edit %}
                        action="/admin/edit/faculty/{{ pk }}"
                    {% else %}
                        action="/admin/add/faculty"
                    {% endif %}
                    method="post">
                {% csrf_token %}
                {{ faculty_form|crispy }}
                <div class="w-100 d-flex justify-content-center">
                    <button class="w-50 btn btn-primary" type="submit">Gönder</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

uniatlas/website/templates/website/adduni.html
{% include 'website/main.html' %}

{% load static %}
{% load crispy_forms_tags %}

<link rel="stylesheet" type="text/css" href="{% static "css/unisozluk_login.css" %}">

{% block content %}

    <form {% if edit %}
        action="/admin/edit/university/{{ pk }}"
    {% else %}
        action="/admin/add/university"
    {% endif %} method="post" class="d-flex flex-column justify-content-center mb-5">
        <div class="d-flex flex-row justify-content-center mt-5 mb-5">
            {% csrf_token %}
            <div class="d-flex flex-column image-edit-card align-self-start">
                <p><br></p>
                <h5 style="font-family: 'Times New Roman'; color:#60475a ">— Fotoğraf Ekle</h5>
                <div class="text-center">
                    <img src="{% static 'images/2404969.jpg' %}" alt="" class="img-thumbnail" style="width: 320px">
                </div>
                <p><br></p>
                <div class="custom-file mt-2">
                    {{ form.image|as_crispy_field }}
                </div>
                <p><br></p>
            </div>
            <div class="d-flex flex-column">
                <div class="d-flex flex-row justify-content-center">
                    <div class="w-100">
                        {{ form.name | as_crispy_field }}
                        {{ form.city | as_crispy_field }}
                        {{ form.history | as_crispy_field }}
                        {{ form.types | as_crispy_field }}
                    </div>
                </div>
            </div>
        </div>
        <div class="w-100 d-flex justify-content-center">
            <button class="btn btn-primary w-25" type="submit">Gönder</button>
        </div>
    </form>


{% endblock %}

uniatlas/website/templates/website/controlpanel.html
{% include 'website/main.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/controlpanel.css' %}">
{% block content %}

    <header class="result-header" style="font-family:'Comic Sans MS'" color="#120923">KONTROL PANELİ</header>

    <div id="control-exp" class="d-flex justify-content-left">
        <p class="text-area" style="font-family:'Comic Sans MS'">Üniversite ekleme, çıkarma ve güncelleme.</p>
    </div>


    <div class="row justify-content-md-center">
        <div class="col-md-9 ">
            <div class="d-flex flex-row-reverse">
                <div id="add-uni-btn" class="d-flex flex-row-reverse mr-1">
                    <a href="/admin/add/departmant">
                        <button class="btn btn-success btn-sm" type="button">Departman Ekle</button>
                    </a>
                </div>
                <div id="add-uni-btn" class="d-flex flex-row-reverse mr-1">
                    <a href="/admin/add/faculty">
                        <button class="btn btn-success btn-sm" type="button">Fakülte Ekle</button>
                    </a>
                </div>
                <div id="add-uni-btn" class="d-flex flex-row-reverse mr-1">
                    <a href="/admin/add/university">
                        <button class="btn btn-success btn-sm" type="button">Üniversite Ekle</button>
                    </a>
                </div>
            </div>

        <form action="/admin/controlpanel" method="get">
            <div class="searchbar">
                <div class="input-group mb-3">
                    <input name="search_key" type="text" class="form-control" placeholder="Arama"
                           aria-label="Recipient's username"
                           aria-describedby="basic-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit">Ara</button>
                    </div>
                </div>
            </div>
        </form>
            <div class="table-responsive">
                <table id="table" class="table table-bordered ">
                    <thead>
                    <tr class="result-table-header">
                        <th scope="col">Üniversite</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    {% for datum in data %}
                        {% if datum.type == 'university' %}
                            <tr class="result-table-row" data-tt-id="{{ datum.id }}" data-tt-level="0">
                                <td>{{ datum.name }}</td>
                                <td class="result-button-group">
                                    <a href="/admin/edit/university/{{ datum.pk }}">
                                        <button type="button" class="btn btn-info btn-sm">Güncelle</button>
                                    </a>
                                    <a href="/admin/delete/university/{{ datum.pk }}">
                                        <button type="button" class="btn btn-danger btn-sm">SİL</button>
                                    </a>
                                </td>
                            </tr>
                        {% elif datum.type == 'faculty' %}
                            <tr class="result-table-row" data-tt-id="{{ datum.id }}" data-tt-parent-id="{{ datum.parent_id }}" data-tt-level="1">
                                <td style="padding-left: 50px">{{ datum.name }}</td>
                                <td class="result-button-group">
                                    <a href="/admin/edit/faculty/{{ datum.pk }}">
                                        <button type="button" class="btn btn-info btn-sm">Güncelle</button>
                                    </a>
                                    <a href="/admin/delete/faculty/{{ datum.pk }}">
                                        <button type="button" class="btn btn-danger btn-sm">SİL</button>
                                    </a>
                                </td>
                            </tr>
                        {% else %}
                            <tr class="result-table-row" data-tt-id="{{ datum.id }}" data-tt-parent-id="{{ datum.parent_id }}" data-tt-level="2">
                                <td style="padding-left: 75px">{{ datum.name }}</td>
                                <td class="result-button-group">
                                    <a href="/admin/edit/departmant/{{ datum.pk }}">
                                        <button type="button" class="btn btn-info btn-sm">Güncelle</button>
                                    </a>
                                    <a href="/admin/delete/departmant/{{ datum.pk }}">
                                        <button type="button" class="btn btn-danger btn-sm">SİL</button>
                                    </a>
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <script>
		com_github_culmat_jsTreeTable.register(this)
		treeTable($('#table'))
    </script>
{% endblock %}

uniatlas/website/templates/website/home.html
{% include 'website/main.html' %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/home.css' %}">

{% block content %}
<!DOCTYPE html>
<html>

<body>

<div class="d-flex flex-column">
    <img src="{% static 'images/Sunu1.jpg' %}">

</div>

</body>
</html>

{% endblock %}

uniatlas/website/templates/website/login.html
{%  include 'website/main.html' %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/unisozluk_login.css' %}">

{% block content %}
<div class="jumbotron" style=" background: none">
    <div class="d-flex justify-content-center">
        <div class="card">
            <div class="card-body">
                <div class="d-flex flex-row">
                    <div class="d-flex flex-column">
                        <img class="img-fluid login-img" src="{% static 'images/loginimg.jpg' %}" alt=""/>
                    </div>
                    <form class="d-flex flex-column align-items-center align-self-center login-info-panel" method="POST"
                          action="">
                        <h1 class="mb-md-5" style="color: #60475a; font-family: 'Times New Roman'">Üye Girişi</h1>
                        {% csrf_token %}
                        <input name="username" type="text" class="form-control mb-sm-2" placeholder="Kullanıcı Adı"
                               aria-label="Username" aria-describedby="basic-addon1">

                        <input name="password" type="password" id="inputPassword6" placeholder="Şifre"
                               class="form-control mx-sm-2" aria-describedby="passwordHelpInline">

                        <input class="btn btn-primary mt-3" type="submit"
                               style="background-color: #59788E; width: 150px"
                               value="Giriş">

                        <a href="signup" class="mt-4">Henüz üye olmadın mı? Nasıl olur?</a>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

uniatlas/website/templates/website/resultpage.html
{% include 'website/main.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/resultpage.css' %}">
{% block content %}

    <div class="d-flex flex-column justify-content-center">
        <header class="result-header" style="font-family:'Comic Sans MS'" color="#120923">Sonuçlar</header>
        <div class="row justify-content-md-center">
            <div class="col-md-9 ">
                <div class="table-responsive">
                    <table class="table table-bordered ">
                        <thead>
                        <tr class="result-table-header">
                            <th scope="col">Derece</th>
                            <th scope="col">Alan</th>
                            <th scope="col">Bölüm</th>
                            <th scope="col">Üniversite</th>
                            <th scope="col">Şehir</th>
                            <th scope="col">Burs</th>
                            <th scope="col">Taban Puanı</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for datum in data %}
                            <tr class="result-table-row">
                                <td>{{ datum.get_total_year_display }}</td>
                                <td>{{ datum.faculty.get_edu_field_display }}</td>
                                <td>{{ datum.name }}</td>
                                <td>{{ datum.faculty.university.name }}</td>
                                <td>{{ datum.faculty.university.city }}</td>
                                <td>{{ datum.get_scholarship_display }}</td>
                                <td>{{ datum.score }}</td>
                                <td class="result-button-group">
                                    {% if is_authenticated %}
                                        <button type="button" class="btn btn-success btn-sm">EKLE</button>
                                        <button type="button" class="btn btn-info btn-sm">ÜniSözlük</button>
                                    {% endif %}
                                </td>
                            </tr>

                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}